name: CI/CD Docker

on:
  push:
    branches: ["main"]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout codul
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instaleaza Node si ruleaza testele
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # 3. Login in Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Seteaza tag-uri pentru imagine 
      - name: Set image tags
        id: vars
        run: |
          IMAGE_NAME="DeliaSpridon/deploy_test/deploy_test"
          GIT_SHA="${GITHUB_SHA::7}"
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tag_latest=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          echo "tag_sha=${IMAGE_NAME}:${GIT_SHA}" >> $GITHUB_OUTPUT

      # 5. Build + push imagine Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.tag_latest }}
            ${{ steps.vars.outputs.tag_sha }}
